services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file: .env
  web:
    build: .
    command: sh entrypoint-web.sh
    volumes:
      - $PWD:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - dict
      - vocabulary
    env_file: .env
    restart: unless-stopped

  dict:
    build: .
    command: dictd -d nodetach --listen-to 0.0.0.0 --port 2628

  vocabulary:
    build: .
    command: sh entrypoint-vocabulary.sh

volumes:
  db-data:

networks:
  bridge:

