services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
#      - "POSTGRES_HOST_AUTH_METHOD=trust"
  web:
    build: .
    command: python -m uvicorn api.server:app --port=8000 --host=0.0.0.0
    volumes:
      - $PWD:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - dict
      - training
    environment:
      - "POSTGRES_HOST=db"
      - "POSTGRES_DBNAME=postgres"
      - "POSTGRES_PORT=5432"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "SECRET_KEY=secret"
    restart: unless-stopped

  dict:
    build: .
    command: dictd -d nodetach --listen-to 0.0.0.0 --port 2628

  training:
    build: .
    command: python multiconn-server.py 0.0.0.0 65432

networks:
  bridge:

