"""bword.count default 0

Revision ID: 61d3652d10d2
Revises: ffba6c1ae883
Create Date: 2023-06-14 16:57:50.921633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d3652d10d2'
down_revision = 'ffba6c1ae883'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
