"""create models for new structure

Revision ID: 7dcdbf6fb41b
Revises: 
Create Date: 2024-03-19 20:19:16.260580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcdbf6fb41b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('sentences_count', sa.Integer(), nullable=False),
    sa.Column('words_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parrot_settings',
    sa.Column('last_word_id', sa.Integer(), nullable=False),
    sa.Column('last_sentence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('username')
    )
    op.create_table('word',
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('lem', sa.String(length=255), nullable=False),
    sa.Column('declination', sa.JSON(), nullable=False),
    sa.Column('definition', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lem')
    )
    op.create_table('flashcard',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_word', sa.String(length=200), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('definition', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence',
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcard_word',
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcard.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence_flashcard',
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcard.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence_word',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence_word')
    op.drop_table('sentence_flashcard')
    op.drop_table('flashcard_word')
    op.drop_table('sentence')
    op.drop_table('flashcard')
    op.drop_table('word')
    op.drop_table('user')
    op.drop_table('parrot_settings')
    op.drop_table('book')
    # ### end Alembic commands ###
