"""add path to book

Revision ID: b66efb0df8a8
Revises: a9722ed99bb3
Create Date: 2023-04-27 18:26:53.358239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66efb0df8a8'
down_revision = 'a9722ed99bb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('path', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'path')
    # ### end Alembic commands ###
