"""changed column type text

Revision ID: dc88e8e63738
Revises: 9b0645c3853f
Create Date: 2023-06-20 13:38:38.950181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc88e8e63738'
down_revision = '9b0645c3853f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_content', 'sentence', type_=sa.Text())
    op.alter_column('sentence', 'text', type_=sa.Text())
    op.alter_column('sentence', 'translation', type_=sa.Text())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_content', 'sentence', type_=sa.String(255))
    op.alter_column('sentence', 'text', type_=sa.String(255))
    op.alter_column('sentence', 'translation', type_=sa.String(255))
    # ### end Alembic commands ###
